### ISSUE TITLE
Feature: read reporter config from cypress config

### ISSUE THREAD

**Issue by cc-ebay** [YOU54F/cypress-multi-reporters#101]
We are running cypress on multiple localized version of the website.

It would be useful to be able to use `plugins/index.js` to set options for the reports.

For example with :
```
plugins/index.js:

module.exports = (on, config) => {
    
  // some logic to det `locale`

  config.mochawesomeReporterOptions = {
    reportDir: `.reports/${locale}`,
  }

  config.mochaJunitReporterReporterOptions = {
    mochaFile: `./junit-${locale}.xml`,
  }
  
   return config;
}
```

**Comment by YOU54F** [comment]
Thanks for the report! Happy to accept contributions :)

**Comment by YOU54F** [comment]
Will be archiving this repo today, thanks for the issue raising

Code is now held here https://github.com/YOU54F/cypress-plugins/tree/master/cypress-multi-reporters
