### ISSUE TITLE
Feature: read the config from a .js file

### ISSUE THREAD

**Issue by cc-ebay** [YOU54F/cypress-multi-reporters#105]
This may be simpler to implement than #101:

In order to dynamically configure the reporters  instead of having a static JSON file it would be great to be able to use full Javascript. Think `.babelrc` vs  `.babelrc.js`. In this way the path of the reporter output could be dynamically read from an environment variable.

**Comment by cc-ebay** [comment]
Ah... It looks like it was already implemented: 
https://github.com/YOU54F/cypress-multi-reporters/tree/125db1741b871c1eb7083c212dfe3cb93e25979e/lib/MultiReporters.js#L160-L162

Closing!

**Comment by cc-ebay** [comment]
I ended up using the example in #106 
And a `runall.sh` file:
```bash
#!/bin/bash
#By default run on all site but you can pass a paramenter
args="$@"
allsites="US UK AU"
sites=${args:-$allsites}

echo "Will run on $sites"

success=0
for site in $sites
do
    echo "Running on $site"
    export SITE_LOCALE="$site"
    npx cypress run
    ret_code=$?
    if [ $ret_code -ne 0 ]; then
         echo "Run for $site - Exited with and ERROR: $ret_code"
        success=$ret_code
    fi
done
echo "All sites finished running. Exiting with $success"
exit $success
```

**Comment by YOU54F** [comment]
These are my favourite kind of issues. Top detective work, no need for me to do owt, and updating the documentation as well! Legend @cc-ebay 

You must be my work colleague’s doppleganger 😂🤘🏽
