### ISSUE TITLE
should `.reports` be `./reports` in the README?

### ISSUE THREAD

**Issue by kris-luminar** [YOU54F/cypress-multi-reporters#168]
should `.reports` be `./reports` in the README?

**Comment by YOU54F** [comment]
Yes! Good spot, happy for a PR to update if you have time 

please note I need to archive this repo as it now lives here

https://github.com/YOU54F/cypress-plugins/tree/master/cypress-multi-reporters

**Comment by YOU54F** [comment]
Will be archiving this repo today, thanks for the issue raising

Code is now held here https://github.com/YOU54F/cypress-plugins/tree/master/cypress-multi-reporters
