### ISSUE TITLE
Doesn't work when config file is inside env folder

### ISSUE THREAD

**Issue by vasmos** [YOU54F/cypress-multi-reporters#43]
### Expected behavior
I can put my config files into cypress/config folder and have separate files for each environment but then this plugin doesn't work
### Actual behavior
Getting an error saying:
Cannot set property 'mochaFile' of undefined
TypeError: Cannot set property 'mochaFile' of undefined

### Steps to reproduce the behavior

  1. Create config folder in cypress and configure plugin to use config files based on env variable
  2. Run tests with cypress-multi-reporters as a reporter and see above error is thrown

**Comment by YOU54F** [comment]
have you tried setting `--reporter-options configFile=<pathToConfig>` as per the docs

**Comment by brettz9** [comment]
Maybe this should be closed unless @vasmos can answer re: the steps to reproduce?

**Comment by YOU54F** [comment]
Closing due to lack of reproducible example. If anyone comes across this issue and wants to reopen, please provide a working example and we can investigate 🤙
