### ISSUE TITLE
configuration for @scoped reporters

### ISSUE THREAD

**Issue by alvaromartmart** [YOU54F/cypress-multi-reporters#77]
Is there some way of specifying options for scoped reporters?
I have this `reporter.config.json`
``` json
{
  "reporterEnabled": ["mochawesome", "@org/custom-rep"],
  "mochawesomeReporterOptions": {
    "charts": true,
    "overwrite": false,
    "html": false,
    "json": true,
    "reportDir": "reports"
  },
  "@org/customRepReporterOptions": {
    "arg1": true
  }
}
```
> Note: I have also tried using just "customRepReporterOptions".

### Expected behavior
`customRepReporterOptions` should be passed to the `@org/custom-rep` reporter.

### Actual behavior
The reporter doesn't receive the options.

### Information about the Issue
Everything worked until I added the scope to my custom reporter.

**Comment by alvaromartmart** [comment]
oh I see... I guess this line removes the @
https://github.com/YOU54F/cypress-multi-reporters/blob/4fcbc7f4e1da370ec002ed5adb10876744f0e005/lib/MultiReporters.js#L204

So I can specify the configuration using
```json
{
  "reporterEnabled": ["mochawesome", "@org/custom-rep"],
  "mochawesomeReporterOptions": {
    "charts": true,
    "overwrite": false,
    "html": false,
    "json": true,
    "reportDir": "reports"
  },
  "orgCustomRepReporterOptions": {
    "arg1": true
  }
}
```

**Comment by YOU54F** [comment]
Hey, thanks for the investigation! I assume this is resolved now. Is that a suitable workaround to drop the @ and would you interested in making a readme update to help others? 
Many thanks!

**Comment by Roemer** [comment]
Maybe add an example for a local reporter as well: `reporters/myreporter.js` would then be `reportersMyreporterJsReporterOptions`

**Comment by YOU54F** [comment]
@Roemer - Would welcome a docs contribution if you would like to add one 👍🏾
