### ISSUE TITLE
cypress-multi-reporters not considering the reporterOptions set in config file 

### ISSUE THREAD

**Issue by sai-tej** [YOU54F/cypress-multi-reporters#82]
### Expected behavior
The reporterOptions set in report-config.json file should be considered
### Actual behavior
The options set in repor-config are not being considered
### Information about the Issue
I'm trying to use mochawesome as well as mocha-junit-reporters for generating both html as well as xml reports for our tests. I specified cypress-multi-reporters as the reporter in cypress.json and in the commandline, I'm passing the report-config file. 
I get both the reports but they're being created in the default locations and html:false is also not being considered.
Please take a look at both the files.

cypress.json
```
{
    "baseUrl": "http://localhost:4200",
    "testFiles": "**/*.test.js",
    "chromeWebSecurity": true,
    "requestTimeout": 90000,
    "video": false,
    "reporter": "../../../node_modules/cypress-multi-reporters",
    "firefoxGcInterval": null
}
```
chromeReportconfig
```
{
  "reporterEnabled": "../../../node_modules/mochawesome, ../../../node_modules/mocha-junit-reporters",
  "reporterOptions": {
    "mochawesomeReporterOptions": {
      "reportDir": "results/results_chrome/",
      "quiet": true,
      "overwrite": false,
      "html": false,
      "json": true
    },
    "mochaJunitReporterReporterOptions": {
      "mochaFile": "results/junits/test_results[hash].xml",
      "toConsole": false
    }
  }
}
```
finally starting the tests with this
```cypress run --headless --browser chrome --reporter-options configFile=chromeReportconfig.json --project ./cypress/integration --spec ./cypress/integration/cypress/integration/home/**/*.test.js```

### Steps to reproduce the behavior

  1. Run any test with above config.
  
Appreciate your time and help here. Thanks

**Comment by YOU54F** [comment]
HEY @sai-tej 

I will take a look. 

First thing to note is `mocha-junit-reporters` is deprecated 

https://www.npmjs.com/package/mocha-junit-reporters

```
This package has been deprecated
Author message:

Please revert back to using mocha-junit-reporter@1.23.0 or greater as the Mocha6+ compatibility fix has now been merged.
```

Please use https://www.npmjs.com/package/mocha-junit-reporter instead.

What is your product structure like

I am assuming from your setup that you have

`/some/nested/folder/cypress/integration/tests/*.test.js`
`/some/nested/folder/cypress/cypress.json`
`/some/nested/folder/chromeReportconfig.json`
`package.json` (with cypress-multi-reporters and mocha-junit-reporters but not cypress?)

And to run this

`cypress run --headless --browser chrome --reporter-options configFile=chromeReportconfig.json --project ./cypress/integration --spec ./cypress/integration/cypress/integration/home/**/*.test.js`

You have cypress installed globally?

Is this spec path correct? as it contains `cypress/integration` twice

`--spec ./cypress/integration/cypress/integration/home/**/*.test.js`

Your setup is quite particular so it is not as simple as your example sounds, I would advise creating a repository with your setup, showing the incorrect behaviour.

**Comment by YOU54F** [comment]
You can find a repo that you can fork and create an example.

https://github.com/YOU54F/cypress-slack-reporter-issues

If you run `make test-multi-reporters`, I think it should have replicated what your project setup and what you wanted to acheive?

**Comment by sai-tej** [comment]
Hi @YOU54F , thanks a lot for the response and apologies for the delay.

I've created the example in https://github.com/sai-tej/cypress-slack-reporter-issues with folder structure similar to my project. Could you please have a look?

**Comment by sai-tej** [comment]
I ran `make test-multi-reporters` and I could reproduce my issue. The directory option I gave in chromeReportConfig is not being considered. Your help and time to resolve my issue are appreciated.

**Comment by YOU54F** [comment]
It probably won’t be until next week as I’m on holiday this week, but thank you for the repro.

**Comment by sai-tej** [comment]
@YOU54F sure, happy holiday!

**Comment by sai-tej** [comment]
Hi @YOU54F did you get a chance to look into this?

**Comment by YOU54F** [comment]
please see the following

https://github.com/YOU54F/cypress-slack-reporter-issues/pull/2/commits/4f2f1a3cac52a44091b318dd3d50ed68f03cdad5

there is a couple of issues.

1. this path `"reporter": "../../../node_modules/cypress-multi-reporters",` takes you outside of your project root.
2. in reporterOpts, the reporterEnabled key is relative to the cypress-multi-reporters package in node_modules, not it's position of your config file. 
3. in reporterrOpts, you don't need `reporterOptions` and wrapping the other reporters options in it, means they wont be set
